### ISSUE TITLE
Has this paper been published yet?

### ISSUE THREAD

**Issue by liguge** [PHM-Code/MWA-CNN#1]

**Comment by PHM-Code** [comment]
No, this paper is under review.

**Comment by liguge** [comment]
Excuse me, can you easily reveal which journal you submitted your manuscript to?



At 2022-07-11 10:31:38, "PHM-Code" ***@***.***> wrote:

No, this paper is under review.

**Comment by liguge** [comment]
Excuse me, can you easily reveal which journal you submitted your manuscript to?













At 2022-07-11 10:31:38, "PHM-Code" ***@***.***> wrote:

No, this paper is under review.

**Comment by PHM-Code** [comment]
MSSP

**Comment by liguge** [comment]
thanks for your answer！



在 2022-07-11 10:51:22，"PHM-Code" ***@***.***> 写道：

MSSP

**Comment by liguge** [comment]
可以加个微信一起交流吗？我也是研究故障诊断的一员。我的vx是 huantaihechao



在 2022-07-11 10:51:22，"PHM-Code" ***@***.***> 写道：

MSSP
